# Generated by Django 4.2.4 on 2023-08-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfig',
            options={'verbose_name_plural': 'User Configuration'},
        ),
        migrations.AddField(
            model_name='userconfig',
            name='generation_time',
            field=models.DateTimeField(null=True),
        ),
    ]
